vim.defer_fn(function()
    require('setups.barbar')
    require('setups.lualine')
    require('setups.nvim-tree')
    require('setups.telescope')
    require('setups.nvim-treesitter')
    require('setups.mason')
    require('setups.mason-lspconfig')
    require('setups.neodev')
end, 0)
